### ISSUE TITLE
You are violating the license of onlyfans-dl

### ISSUE THREAD

**Issue by k0rnh0li0** [jordon31/OF-SCR#1]
[onlyfans-dl](https://github.com/k0rnh0li0/onlyfans-dl), the project upon which the code in this repository is almost entirely based, is licensed under the terms of GPLv3. You have copied our code and made trivial changes to the script and the readme, which is no problem, except you also deleted the license text. Under the terms of GPLv3, you are legally obligated to also release your modified version of our code under the terms of the GPLv3. Please fix this as soon as you are able.

Also, the GPL does not require you to credit us for copying our code and making changes to it, but it is extremely lame how you just deleted all forms of credit to the original project you got 95% of this code from. Stop being a skid.

Finally, it was really annoying having to go through and delete all your spam comments. Please stop spamming links to your repo in the issues of my repo or I'm reporting you to GitHub.

**Comment by jordon31** [comment]
✔ 

https://github.com/jordon31/OF-SCR/blob/main/README.md#gpl-3

**Comment by jadenquinn** [comment]
> [onlyfans-dl](https://github.com/k0rnh0li0/onlyfans-dl), the project upon which the code in this repository is almost entirely based, is licensed under the terms of GPLv3. You have copied our code and made trivial changes to the script and the readme, which is no problem, except you also deleted the license text. Under the terms of GPLv3, you are legally obligated to also release your modified version of our code under the terms of the GPLv3. Please fix this as soon as you are able.
> 
> Also, the GPL does not require you to credit us for copying our code and making changes to it, but it is extremely lame how you just deleted all forms of credit to the original project you got 95% of this code from. Stop being a skid.
> 
> Finally, it was really annoying having to go through and delete all your spam comments. Please stop spamming links to your repo in the issues of my repo or I'm reporting you to GitHub.

The very existence of Onlyfans downloaders is a violation of every copyright law put forth by the creators themselves, and probably the Onlyfans TOS, this is just cringe.

**Comment by jordon31** [comment]
> > [onlyfans-dl](https://github.com/k0rnh0li0/onlyfans-dl), the project upon which the code in this repository is almost entirely based, is licensed under the terms of GPLv3. You have copied our code and made trivial changes to the script and the readme, which is no problem, except you also deleted the license text. Under the terms of GPLv3, you are legally obligated to also release your modified version of our code under the terms of the GPLv3. Please fix this as soon as you are able.
> > Also, the GPL does not require you to credit us for copying our code and making changes to it, but it is extremely lame how you just deleted all forms of credit to the original project you got 95% of this code from. Stop being a skid.
> > Finally, it was really annoying having to go through and delete all your spam comments. Please stop spamming links to your repo in the issues of my repo or I'm reporting you to GitHub.
> 
> The very existence of Onlyfans downloaders is a violation of every copyright law put forth by the creators themselves, and probably the Onlyfans TOS, arguing about this is just cringe.

I know this, but I satisfied him.
