### ISSUE TITLE
Inconsistent folder capitalization

### ISSUE THREAD

**Issue by rogueralsha** [jordon31/OF-SCR#11]
When running this on a Linux server, this program creates both Media/Photos, and Media/photos, which are two different folders on Linux, and then only puts files in Media/photos. The script should be consistent with capitalization of folders.

**Comment by Mrjelly13** [comment]
it also creates a  Media/Photos and a  Media/photos and only puts it in Media/photos.

**Comment by jordon31** [comment]
thanks for the report .. now comes out normal 

![image](https://github.com/jordon31/OF-SCR/assets/94505651/9270d645-c965-4f3a-ae8d-ac5e0212d0b9)
