### ISSUE TITLE
ERROR Access denied

### ISSUE THREAD

**Issue by cgg520449** [jordon31/OF-SCR#16]
An error occurred while using today
![Snipaste_2023-08-22_11-31-07](https://github.com/jordon31/OF-SCR/assets/116888205/b624d0e3-4a79-49df-9e9f-ea67e254bc1e)

**Comment by jordon31** [comment]
Please check the Auth file well and refresh the onlyfans page to see if it knocked you out

**Comment by cgg520449** [comment]
> 



> Please check the Auth file well and refresh the onlyfans page to see if it knocked you out

I logged out, then logged back in to the OnlyFans website. reconfigured the content of the "auth.json",It's working
