### ISSUE TITLE
no module named emoji

### ISSUE THREAD

**Issue by j-ktz** [jordon31/OF-SCR#17]
just installed and getting this error. 
`  File "/Users/jktz/OF-SCR-main/of-scr.py", line 10, in <module>
    import emoji
ModuleNotFoundError: No module named 'emoji'`

**Comment by rhcp011235** [comment]
You need to run

`pip install -t requirements.txt
 pip3 install -t requirements.txt`

I assume you did not do that.

**Comment by j-ktz** [comment]
I see requirements.txt in the  folder but when I run  pip install it throws this error.
`Johns-MacBook-Pro:OF-SCR-main jktz$ pip3 install -t requirements.txt
ERROR: Target path exists but is not a directory, will not continue.
Johns-MacBook-Pro:OF-SCR-main jktz$ pip install -t requirements.txt
ERROR: Target path exists but is not a directory, will not continue.`

**Comment by rhcp011235** [comment]
Sorry

pip install -r requirements.txt
pip3 install -r requirements.txt

**Comment by rhcp011235** [comment]
This is in the readme btw.

**Comment by j-ktz** [comment]
Thank you!
