### ISSUE TITLE
suggestion!

### ISSUE THREAD

**Issue by lilfmdude** [jordon31/OF-SCR#2]
I don't know if it's okay to post here, but recently, I have followed a lot of girls. However, a lot of them promote each other at the end of each post, where they feature a promoted girl and leave a #ad. Is there any way we can skip those promotions?

**Comment by jordon31** [comment]
do you have a free profile for an example? which I don't quite understand

**Comment by lilfmdude** [comment]
Here is an example: https://onlyfans.com/nina_blaze. She does shoutouts for other creators at the end of her posts. In the description of every shoutout, she puts a #ad at the end. Is there any way we can skip these? If not, it's okay.

**Comment by jordon31** [comment]
it is possible to add a "@" filter to avoid posts with another user's mention.. i'll add it when i make the next update.. i think soon

**Comment by jordon31** [comment]
Added.. install "pip install prompt_toolkit" and run

**Comment by lilfmdude** [comment]
thank you so much! trying it now will let you know how it goes.

**Comment by lilfmdude** [comment]
it works amazingly thank you anyway I can select all? so i don't have to keep selecting a user one by one?

**Comment by jordon31** [comment]
i removed because i had some problems.. but i will put it

**Comment by lilfmdude** [comment]
perfect thanks man if u can add a timer that starts to download the next persons profile automatically instead of pressing C would be nice sorry if I'm being annoying but overall its perfect

**Comment by jordon31** [comment]
https://github.com/jordon31/OF-SCR/blob/main/Change%20Version.md#version-04

**Comment by lilfmdude** [comment]
thanks! will try this new version out!

**Comment by lilfmdude** [comment]
i get this error 

An error has occurred: [WinError 183] Cannot create a file when that file already exists: 'profiles/stellareedfree/TaggedPosts/photos/2023'
Traceback (most recent call last):
  File "c:\Users\Mikey\Desktop\OF-SCR-main\OF-SCR-main\of-scr.py", line 591, in <module>
    media_downloaded, skipped_posts = download_posts(photo_posts, False, pbar, skip_tagged_posts=False, tag_folder="TaggedPosts") #Photo Post  -- True or False  -- (to decide if you want to skip posts with the tag "skip_tagged_posts)=")
  File "c:\Users\Mikey\Desktop\OF-SCR-main\OF-SCR-main\of-scr.py", line 392, in download_posts
    was_downloaded = future.result()
  File "C:\Users\Mikey\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Users\Mikey\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\Mikey\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\Users\Mikey\Desktop\OF-SCR-main\OF-SCR-main\of-scr.py", line 315, in download_media
    folder_name = get_year_folder(timestamp, type, tag_folder=tag_folder)
  File "c:\Users\Mikey\Desktop\OF-SCR-main\OF-SCR-main\of-scr.py", line 272, in get_year_folder
    assure_dir(photo_path)
  File "c:\Users\Mikey\Desktop\OF-SCR-main\OF-SCR-main\of-scr.py", line 60, in assure_dir
    os.mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'profiles/stellareedfree/TaggedPosts/photos/2023'

**Comment by lilfmdude** [comment]
seems like i fixed this ignore this all i did was chance the skip tagged post to true and it started to work again

**Comment by jordon31** [comment]
how did you get this error?

**Comment by lilfmdude** [comment]
i downloaded ur new version as is and ran it normally and gave me that
