### ISSUE TITLE
ERROR: Access denied

### ISSUE THREAD

**Issue by misterdrippy** [jordon31/OF-SCR#4]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~      (^.^) Hello! :>     ~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

x

ERROR: Access denied.
PS E:\1 Onlyfans\OF-SCR-main>

This is the error I get when I try to run of-scr.py in the folder. 

I tried using administrator to run Powershell and everything. Is it an Onlyfans API change? I don't know. Maybe i'm missing something obvious since i'm kind of a noob at Python, but I just wanted to let you know about it.

**Comment by jordon31** [comment]
Have you seen the video?

**Comment by misterdrippy** [comment]
been a busy few weeks so i didn't get to respond but yeah i rewatched the entire video and I still got the same problem.....is it onlyfans API changes? or am i doing something wrong, i'm kind of a noob at python so i hope i don't sound dumb

**Comment by jordon31** [comment]
Hi sir.. i'm update this version.. soon 0,5 version.. thanks for using my script

**Comment by jordon31** [comment]
hi.. check new video and download new version and tell me 

https://www.youtube.com/watch?v=JNKRDsodCTc
