### ISSUE TITLE
error when i select all

### ISSUE THREAD

**Issue by lilfmdude** [jordon31/OF-SCR#7]
when i select the *** download All models***  it works but after a while it crashes and i get this error 

An error has occurred: 'text'
Traceback (most recent call last):
  File "C:\Users\mikep\Desktop\OF-SCR-main\of-scr.py", line 646, in <module>
    media_downloaded = download_posts(photo_posts, False, pbar)
  File "C:\Users\mikep\Desktop\OF-SCR-main\of-scr.py", line 396, in download_posts
    if post["text"] is not None and ("@" in post["text"].lower() or "#adv" in post["text"].lower() or "#ad" in post["text"].lower()):
KeyError: 'text'

also thanks for keeping this updated! 

EDIT: i find the user: Meepmomentt (this is the user thats crashing it for some reason)

**Comment by jordon31** [comment]
it only happens to you with "meepmomentt" 

you have telegram?

**Comment by lilfmdude** [comment]
no i do not have telegram

**Comment by jordon31** [comment]
I also made this profile .. same problem.. I'll let you know

**Comment by jordon31** [comment]
I solved this problem.. thanks for pointing it out.. then release an update
